CREATE TABLE [errorqueue] (
[id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[acid] NVARCHAR(36)  NULL,
[date] TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
[type] NVARCHAR(20)  NOT NULL,
[source] NVARCHAR(50)  NOT NULL,
[page] iNTEGER  NOT NULL,
[pid] NVARCHAR(20)  NULL,
[tid] NVARCHAR(20)  NULL,
[uploadby] NVARCHAR(20)  NULL,
[dststore] NVARCHAR(50)  NULL,
[errormessage] NVARCHAR(50)  NULL
)